version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tasktracker
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasktracker
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
    ports:
      - "8080:8080"

  ui:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  db_data:
